#!/bin/sh

WORK_DIR=`dirname $0`

KEYSTORE=~/app.keystore
KEYALIAS=app
CONFIG=${WORK_DIR}/config
ZIPALIGN=${ANDROID_HOME}/build-tools/20.0.0/zipalign

if [ -f $CONFIG ]; then
  . $CONFIG
fi

for apk in ${WORK_DIR}/*-release-unsigned.apk; do
  UNALIGNED=`echo "$apk" | sed 's/release-unsigned\.apk$/release-unaligned.apk/;'`
  PACKAGE=`echo "$apk" | sed 's/release-unsigned\.apk$/release.apk/;'`

  cp $apk $UNALIGNED
  jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $KEYSTORE $UNALIGNED $KEYALIAS
  rm $PACKAGE
  $ZIPALIGN -v 4 $UNALIGNED $PACKAGE
done
